import { createAgentParticipant } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/arena/agent-participant.ts";
import { playGame } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/arena/runner.ts";
import { loadCatalog } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/arena/scenario.ts";
import { createLlmBot } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/bots/llm-bot.ts";
import { loadConfig } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/engine/config.ts";
import { createClaudeCliClient } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/src/llm/claude-cli.ts";
let calls = 0, failures = 0;
const inner = createClaudeCliClient();
const client = { name: inner.name, complete: async (r: any) => { calls++; const x = await inner.complete(r); if (!x.ok) { failures++; console.error("fallo", x.error.message); } return x; } };
const scenario = loadCatalog("/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/config/arena/scenarios.json").find((s) => s.id === "price-buyer-wide")!;
const t0 = Date.now();
const game = await playGame({ scenario, agent: createAgentParticipant({ config: loadConfig("/Users/pablo/development/hackathon/negotiation-ring.worktrees/finish/config/champion.json") }), rival: createLlmBot({ client, persona: "vendedor experimentado, educado pero duro, que concede poco y despacio" }), seed: 1 });
console.log(JSON.stringify({ endReason: game.endReason, rounds: game.rounds, agreement: game.agreement ?? null, calls, failures, seconds: Math.round((Date.now() - t0) / 1000) }));
for (const m of game.transcript) console.log(m.round, m.from, m.action, JSON.stringify(m.offer ?? null), m.from === "rival" ? m.text.slice(0, 90) : "");
