import { BazaarClient } from "/Users/pablo/development/hackathon/negotiation-ring/src/bazaar/client.ts";
import { loadBazaarEnv } from "/Users/pablo/development/hackathon/negotiation-ring/src/bazaar/env.ts";
const env = loadBazaarEnv();
const c = new BazaarClient({ url: env.url, key: env.key! });
const me: any = await c.raw("GET", "/api/me");
console.log("affinity", JSON.stringify(me.affinity), "open_threads", JSON.stringify(me.open_threads), "frozen", me.frozen, "badges", JSON.stringify(me.badges));
console.log("album", JSON.stringify(me.album).slice(0, 600));
console.log("assets", JSON.stringify(me.assets.map((a: any) => `${a.id}:${a.ref}:${a.rarity}:${a.your_value}`)));
const t: any = await c.raw("GET", "/api/threads/184");
console.log("T184", JSON.stringify({ ...t, messages: t.messages?.map((m: any) => ({ sender: m.sender, price: m.price, tick: m.tick, offer: m.offer })) }).slice(0, 2500));
