import { BazaarClient } from "/Users/pablo/development/hackathon/negotiation-ring/src/bazaar/client.ts";
import { loadBazaarEnv } from "/Users/pablo/development/hackathon/negotiation-ring/src/bazaar/env.ts";
import { ThreadSchema, MeSchema, ThreadListSchema } from "/Users/pablo/development/hackathon/negotiation-ring/src/bazaar/schemas.ts";
const env = loadBazaarEnv();
const c = new BazaarClient({ url: env.url, key: env.key! });
const t = await c.raw("GET", "/api/threads/56");
console.log(JSON.stringify(t, null, 1).slice(0, 6000));
const r = ThreadSchema.safeParse(t); console.log("thread parse ok:", r.success, r.success ? "" : JSON.stringify(r.error.issues).slice(0, 1500));
const me = await c.raw("GET", "/api/me"); const rm = MeSchema.safeParse(me); console.log("me ok:", rm.success, rm.success ? "" : JSON.stringify(rm.error.issues).slice(0, 800));
console.log("me keys", Object.keys(me as object), JSON.stringify((me as any).score)?.slice(0,300), (me as any).id, (me as any).team);
const l = await c.raw("GET", "/api/me/threads?status=open"); const rl = ThreadListSchema.safeParse(l); console.log("list ok:", rl.success, rl.success ? "" : JSON.stringify(rl.error.issues).slice(0, 800));
