import { roundInFavor, utility } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/add-agent-architecture/src/engine/issues.ts";
import { enforceOfferGuardrails } from "/Users/pablo/development/hackathon/negotiation-ring.worktrees/add-agent-architecture/src/engine/guardrails.ts";
const hb = [{ name: "p", min: 0, max: 1, direction: "higher-better" as const, weight: 1 }];
const lb = [{ name: "p", min: 0, max: 1000, direction: "lower-better" as const, weight: 1 }];
const v = 0.5 + 5e-12;
console.log("hb round", roundInFavor(hb, { p: v }), "u drop", utility(hb, { p: v }) - utility(hb, roundInFavor(hb, { p: v })));
const r = 99.99999999999;
const out = enforceOfferGuardrails(lb, { role: "buyer", reservation: { p: r } }, { p: 500 });
console.log("buyer res", r, "sent", out.p, "crosses?", out.p > r);
const r2 = 0.1 + 0.2;
const out2 = enforceOfferGuardrails(hb, { role: "seller", reservation: { p: r2 } }, { p: 0 });
console.log("res", r2, "sent", out2.p, "crosses?", out2.p < r2);
