process.loadEnvFile(".env");
const u = process.env.BAZAAR_URL!, k = process.env.BAZAAR_KEY!;
const g = async (p: string) => (await fetch(u + p, { headers: { "X-Team-Key": k } })).json();
const trunc = (x: unknown) => String(JSON.stringify(x)).slice(0, 900);
const me = await g("/api/me"); console.log("ME keys", Object.keys(me), "asset0", trunc(me.assets?.[0]), "album", trunc(me.album), "unlocked", trunc(me.unlocked_dealers), "score", trunc(me.score));
const cat = await g("/api/catalog"); console.log("CAT keys", Object.keys(cat), "set0", trunc({ ...cat.sets?.[0], cards: cat.sets?.[0]?.cards?.slice(0, 2) }), "packs", trunc(cat.packs));
console.log("DEALERS", trunc(await g("/api/dealers")));
console.log("LEVELS", trunc(await g("/api/levels")));
console.log("THREADS", trunc(await g("/api/me/threads")));
console.log("VALUE", trunc(await g("/api/me/value?card=" + cat.sets[0].cards[2].id)));
